baseURL = 'https://lsresource.pages.dev/'
languageCode = 'zh-CN'
title = '林书资源导航'
theme = 'navside'
publishDir = 'public'

disableKinds = ["taxonomy", "term"] # 忽略告警和不生成 category 和 tag 的页面
disablePathToLower    = true
hasCJKLanguage        = true
enableGitInfo         = true



[params]
    author        = "林书"
    submit        = ""                                   # 左侧导航栏的"网站提交"
    about         = "/about"     # 左侧导航栏的"关于导航"页面(./about)    
    enablePreLoad = true		    		             # 网站完全打开前预加载动画
    textPreLoad   = "林书资源导航" 		                # 预加载的动画文字, 只有当enablePreLoad=true时生效    
    expandSidebar = true                                 # 默认展开左侧边导航栏
    displayMode   = 0                                    # 显示模式，0.日间模式，1.深色(夜间)模式。2.实时模式，３.日间模式，４.夜间模式
    cardMode      = true 

[params.seo]
    keywords      = "AI工具导航,资源网站导航,中文互联网资源导航"
    description   = "林书资源导航 - 收录优质AI自媒体、AI工具、AI提示词、AI平台等资源"

[params.images]
    favicon           = "favicon.ico"
    logosPath         = "assets/images/logos"			     # 网站每个导航地址logo存放地址
    defaultLogo       = "assets/images/default.webp"     
    logoExpandLight   = "assets/images/ns-expand-light.png"
    logoExpandDark    = "assets/images/ns-expand-dark.png"
    logoCollapseLight = "assets/images/ns.png"
    logoCollapseDark  = "assets/images/ns.png"    

[params.analytics]
    a51laid = "" # 51.LA 网站统计
    a51lack = "" #

[params.footer]
    copyright = '© 2025, 林书资源导航'

[markup.goldmark.renderer]
    unsafe = true # 忽略告警

